spring:
  application:
    name: yupao
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cpmatch
    username: root
    password: root
  session:
    timeout: 86400
